#!/bin/bash

pkg update -y

xargs -a packages.txt pkg install -y

pkg install -y zsh && chsh -s zsh

ssh-keygen -A

cat > $PREFIX/etc/ssh/sshd_config.d/auth.conf << 'SSH_CONFIG'
PasswordAuthentication no
SSH_CONFIG

pkg install termux-services

sv-enable sshd
sv up sshd
