#!/bin/bash

ssh-copy-id $TERMUX_HOST

cat packages.txt | ssh $TERMUX_HOST "pkg update -y && cat | xargs pkg install -y"

ssh $TERMUX_HOST "pkg install -y zsh && chsh -s zsh"

for script in scripts/*; do
    cat "$script" | ssh $TERMUX_HOST
done

rsync -av .termux/ $TERMUX_HOST:~/.termux/
