#!/bin/bash

DOTFILES_GIT=~/.local/share/dotfiles.git
export GIT_DIR=$DOTFILES_GIT
export GIT_WORK_TREE=~

mkdir -p ~/.local/share
if [ ! -d $DOTFILES_GIT ]; then
    git clone --bare https://github.com/andreivolt/dotfiles.git $DOTFILES_GIT
    git checkout
else
    git pull
fi

git submodule update --init --recursive
